name: OrangeHRM Automation

on:
  push:
    branches:
      - main

jobs:
  selenium-tests:

    runs-on: windows-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 17

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

      - name: Run Test Suite
        run: mvn test